name: slim_data_uri
description: A drop-in, efficient replacement for Dart's Uri with "data:" schemes.
version: 1.0.0
repository: https://github.com/d-markey/slim_data_uri

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
